# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=120),
        ),
    ]
